AdminModule/Controllers/CountryController.cs
using AdminModule.Models;
using AdminModule.Pages;
using AutoMapper;
using Azure;
using BLL.Services;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminModule.Controllers
{
    public class CountryController : Controller
    {
        private readonly ILogger<CountryController> _logger;
        private readonly IMapper _mapper;

        private readonly CountryService _countryService;


        public CountryController(ILogger<CountryController> logger, IMapper mapper, CountryService countryService)
        {
            _mapper = mapper;
            _logger = logger;
            _countryService = countryService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var countries = await _countryService.GetAllCountries();
            var vmCountries = _mapper.Map<IEnumerable<VMCountry>>(countries);

            const int pageSize = 5;
            if (page < 1)
            {
                page = 1;
            }

            int countryCount = vmCountries.Count();
            var pager = new Pager(countryCount, page, pageSize);

            int countrySkip = (page - 1) * pageSize;

            var data = vmCountries.Skip(countrySkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;
            return View(data);
        }

        // GET:
        public ActionResult Create()
        {
            return View();
        }

        // POST:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(VMCountry country)
        {
            try
            {
                var allCountries = await _countryService.GetAllCountries();
                var checkIfCountryExists = allCountries.FirstOrDefault(c => c.Name == country.Name);

                if (checkIfCountryExists == null)
                {
                    await _countryService.AddCountry(
                         new BLL.Models.BLCountry
                         {
                             Name = country.Name,
                             Code = country.Code
                         }
                     );

                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError(string.Empty, "The country already exists!");
                return View(country);

            }
            catch
            {
                return View();
            }
        }

        // GET: 
        public async Task<ActionResult> Edit(int id)
        {
            var country = await _countryService.GetCountryById(id);
            var vmCountry = _mapper.Map<VMCountry>(country);

            return View(vmCountry);
        }

        // POST:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, VMCountry country)
        {
            try
            {
                var dbcountry = await _countryService.GetCountryById(id);

                dbcountry.Code = country.Code;
                dbcountry.Name = country.Name;

                await _countryService.UpdateCountry(dbcountry);
             
                

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: 
        public async Task<ActionResult> Delete(int id)
        {
            var country = await _countryService.GetCountryById(id);
            var vmCountry = _mapper.Map<VMCountry>(country);

            return View(vmCountry);
        }

        // POST: 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _countryService.DeleteCountry(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AdminModule/Views/Country/Create.cshtml
@model VMCountry

@{
    ViewData["Title"] = "Create";
}

<h1 class="row justify-content-center">Create Country</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />  <a class="btn btn-warning" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminModule/Views/Country/Delete.cshtml
@model VMCountry

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this Country?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-warning" asp-action="Index">Back to List</a>
    </form>
</div>

AdminModule/Views/Country/Edit.cshtml
@model VMCountry

@{
    ViewData["Title"] = "Edit";
}

<h1 class="row justify-content-center">Edit Country</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />  <a class="btn btn-warning" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminModule/Views/Country/Index.cshtml
@using AdminModule.Pages;
@model IEnumerable<VMCountry>

@{
    ViewData["Title"] = "Index";
    Pager pager = new Pager();
    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<h1>Countries</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Add country</a>
</p>
<div class="containter">
    @if (pager.TotalPages > 0)
    {
        <h4>Page:</h4>
        <ul class="pagination justify-content-lg-start">
            @for (var pg = pager.StartPage; pg <= pager.EndPage; pg++)
            {
                <li class="page-item @(pg == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Country" asp-action="Index" asp-route-page="@pg">@pg</a>
                </li>
            }
        </ul>
    }
</div>
<br>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>