AdminModule/Controllers/VideoController.cs
using AdminModule.Models;
using AdminModule.Pages;
using AutoMapper;
using Azure.Core;
using BLL.Models;
using BLL.Services;
using DAL.Models;
using DAL.Responses;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace AdminModule.Controllers
{
    public class VideoController : Controller
    {

        private readonly ILogger<VideoController> _logger;
        private readonly IMapper _mapper;

        private readonly VideoService _videoService;
        private readonly TagService _tagService;
        private readonly GenreService _genreService;
        private readonly ImageService _imageService;
        private readonly VideoTagService _videoTagService;

        public VideoController(ILogger<VideoController> logger,IMapper mapper, VideoService videoService, TagService tagService, 
            GenreService genreService, ImageService imageService, VideoTagService videoTagService)
        {
            _mapper = mapper;
            _logger = logger;
            _videoService = videoService;
            _tagService = tagService;
            _genreService = genreService;
            _imageService = imageService;
            _videoTagService = videoTagService;
        }

        private async Task LoadViewBagData()
        {
            var genres = await _genreService.GetAllGenres();
            var vmGenres = _mapper.Map<IEnumerable<VMGenre>>(genres);
            ViewBag.GenreId = new SelectList(vmGenres, "Id", "Name");

            var images = await _imageService.GetAllImages();
            var vmImages = _mapper.Map<IEnumerable<VMImage>>(images);
            ViewBag.ImageId = new SelectList(vmImages, "Id", "Content");
            ViewBag.Images = vmImages;

            var tags = await _tagService.GetAllTags();
            var vmTags = _mapper.Map<IEnumerable<VMTag>>(tags);
            ViewBag.Tags = new SelectList(vmTags, "Id", "Name");
        }

        public async Task<IActionResult> Index(string sortOrder, string searchQuery, bool clearFilter = false,
            int page = 1)
        {

            //Spremanje filtera pomocu cookija 
            if (clearFilter)
            {
                Response.Cookies.Delete("SearchQueryVideo");
                searchQuery = null;
            }

            else if (string.IsNullOrEmpty(searchQuery))
            {
                if (Request.Cookies.TryGetValue("SearchQueryVideo", out string storedSearchQuery))
                {
                    searchQuery = storedSearchQuery;
                }
            }
            else
            {
                //Save
                var cookieOptions = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(7),
                    HttpOnly = true,
                    Secure = true
                };
                Response.Cookies.Append("SearchQueryVideo", searchQuery, cookieOptions);
            }

            var videos = await _videoService.GetAllVideos();
            var sortVideos = _mapper.Map<IEnumerable<VMVideo>>(videos);

            if (!string.IsNullOrEmpty(searchQuery))
            {
                sortVideos = sortVideos.Where(v =>
                    v.Name.Contains(searchQuery)
                    || v.Description.Contains(searchQuery)
                    || v.Genre.Name.Contains(searchQuery)
                    || v.VideoTags.Any(t => t.Tag.Name.Contains(searchQuery)));
            }

            switch (sortOrder)
            {
                case "Name":
                    sortVideos = sortVideos.OrderBy(v => v.Name);
                    break;
                case "Genre":
                    sortVideos = sortVideos.OrderBy(v => v.Genre.Name);
                    break;
                case "Name desc":
                    sortVideos = sortVideos.OrderByDescending(v => v.Name);
                    break;
                case "Genre desc":
                    sortVideos = sortVideos.OrderByDescending(v => v.Genre.Name);
                    break;
                default:
                    sortVideos = sortVideos.OrderByDescending(v => v.Id);
                    break;
            }

            const int pageSize = 5;
            if (page < 1)
            {
                page = 1;
            }

            int videosCount = sortVideos.Count();
            var pager = new Pager(videosCount, page, pageSize);

            int videoSkip = (page - 1) * pageSize;

            var data = sortVideos.Skip(videoSkip).Take(pager.PageSize).ToList();
            ViewBag.Pager = pager;
            //Da bi odrzao sort nakon izmjene stranice
            ViewBag.CurrentSortOrder = sortOrder;


            return View(data);
        }

        public async Task<ActionResult> Create()
        {
            var genres = await _genreService.GetAllGenres();
            var vmGenres = _mapper.Map<IEnumerable<VMGenre>>(genres);
            await LoadViewBagData();
            return View();
        }

        // POST:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(VMVideo video)
        {
            try
            {
                string[] tags = video.NewTags.Split(',');
                var allTags = await _tagService.GetAllTags();
                var existingTags = allTags.Where(t => tags.Contains(t.Name));

                var dbVideo = new BLL.Models.BLVideo
                {
                    Id = video.Id,
                    CreatedAt = video.CreatedAt,
                    Name = video.Name,
                    Description = video.Description,
                    GenreId = video.GenreId,
                    TotalSeconds = video.TotalSeconds,
                    StreamingUrl = video.StreamingUrl,
                    ImageId = video.ImageId,
                    VideoTags = existingTags.Select(t => new BLVideoTag { TagId = t.Id }).ToList()
                };

                foreach (var tag in tags)
                {
                    if (!allTags.Any(t => t.Name == tag))
                    {
                        var newTag = new BLTag { Name = tag };
                        dbVideo.VideoTags.Add(new BLVideoTag { Tag = newTag });
                    }
                }

                await _videoService.AddVideo(dbVideo);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //GET
        public async Task<ActionResult> Edit(int id)
        {
            var video = await _videoService.GetVideoById(id);
            var vmVideo = _mapper.Map<VMVideo>(video);

            await LoadViewBagData();
            return View(vmVideo);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, VMVideo video)
        {
            try
            {
                var dbVideo = await _videoService.GetVideoById(id);

                dbVideo.Id = video.Id;
                dbVideo.Name = video.Name;
                dbVideo.Description = video.Description;
                dbVideo.TotalSeconds = video.TotalSeconds;
                dbVideo.StreamingUrl = video.StreamingUrl;
                dbVideo.GenreId = video.GenreId;
                dbVideo.ImageId = video.ImageId;

               //// Update VideoTags
               //var allTags = await _tagService.GetAllTags();
               //var existingTags = dbVideo.VideoTags.Select(vt => vt.Tag.Name).ToList();
               //
               //var newTags = video.NewTags.Split(',').ToList();
               //
               //var tagsToAdd = newTags
               //    .Where(newTag => !existingTags.Contains(newTag))
               //    .ToList();
               //
               //// Remove old tags
               //foreach (var videoTag in dbVideo.VideoTags.ToList())
               //{
               //    await _videoTagService.DeleteVideoTag(videoTag.Id);
               //}
               //dbVideo.VideoTags.Clear();
               //
               //// Add new tags
               //foreach (var newTag in tagsToAdd)
               //{
               //    if (!string.IsNullOrWhiteSpace(newTag))
               //    {
               //        var tag = allTags.FirstOrDefault(t => t.Name == newTag);
               //        if (tag == null)
               //        {
               //            // Create a new tag if it doesn't exist
               //            tag = new BLTag
               //            {
               //                Name = newTag
               //            };
               //            await _tagService.AddTag(tag);
               //        }
               //        dbVideo.VideoTags.Add(new BLVideoTag { Tag = tag });
               //    }
               //}

                await _videoService.UpdateVideo(dbVideo);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: 
        public async Task<ActionResult> Delete(int id)
        {
            var video = await _videoService.GetVideoById(id);
            var vmVideo = _mapper.Map<VMVideo>(video);

            return View(vmVideo);
        }

        // POST: 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                var dbVideo = await _videoService.GetVideoById(id);
                if (dbVideo == null)
                    return NotFound();

                string deletedTags = string.Join(",", dbVideo.VideoTags
                                        .Select(vt => vt.Tag)
                                        .Where(tag => tag != null)
                                        .Select(tag => tag!.Name));

AdminModule/Views/Video/Create.cshtml
@model VMVideo

@{
    ViewData["Title"] = "Create";

}
<style>

    .scrollable-gallery {
        max-height: 300px;
        overflow-y: auto;
    }

    .selected {
        border: 4px solid #007bff;
    }
</style>


<h1 class=" row justify-content-center">Create Video</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalSeconds" class="control-label"></label>
                <input asp-for="TotalSeconds" class="form-control" />
                <span asp-validation-for="TotalSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreamingUrl" class="control-label"></label>
                <input asp-for="StreamingUrl" class="form-control" />
                <span asp-validation-for="StreamingUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Image</label>
                <input type="hidden" asp-for="ImageId" />
            </div>
            <!-- Gallery -->
            <div class="row scrollable-gallery">
                @foreach (var image in (IEnumerable<VMImage>)ViewBag.Images)
                {
                    <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
                        <img id="image@image.Id"
                         src="@image.Content"
                         class="w-100 shadow-1-strong rounded mb-4"
                         alt="Image"
                         onclick="selectImage('@image.Id', this); viewImage('@image.Content');"
                         style="cursor: pointer;" />
                    </div>
                }
            </div>
            <!-- Gallery -->
            <div class="form-group">
                <label asp-for="NewTags" class="control-label">New Tags:</label>
                <input asp-for="NewTags" class="form-control" />
                <span asp-validation-for="NewTags" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />   <a class="btn btn-warning" asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

<div class="modal fade" id="imageModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <img id="modalImage" class="img-fluid" src="" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var selectedImage = null;

        function selectImage(imageId, element) {
            document.getElementById('ImageId').value = imageId;

            if (selectedImage != null) {
                selectedImage.classList.remove('selected');
            }

            element.classList.add('selected');
            selectedImage = element;
        }

        function viewImage(imageSrc) {
            document.getElementById('modalImage').src = imageSrc;
            $('#imageModal').modal('show');
        }

        //By default i want the first image to be selected if the user doesnt select any image
        window.onload = function () {
            var firstImageElement = document.querySelector('.scrollable-gallery img');
            if (firstImageElement) {
                selectImage(firstImageElement.id.replace('image', ''), firstImageElement);
                //viewImage(firstImageElement.src);
            }
        }
    </script>
}

AdminModule/Views/Video/Delete.cshtml
@model VMVideo

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this Video?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalSeconds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalSeconds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreamingUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreamingUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image.Content)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-warning" asp-action="Index">Back to List</a>
    </form>
</div>

AdminModule/Views/Video/Edit.cshtml
@model VMVideo

@{
    ViewData["Title"] = "Edit";
}

<style>

    .scrollable-gallery {
        max-height: 300px;
        overflow-y: auto;
    }

    .selected {
        border: 4px solid #007bff;
    }
</style>

<h1 class="row justify-content-center">Edit Video</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalSeconds" class="control-label"></label>
                <input asp-for="TotalSeconds" class="form-control" />
                <span asp-validation-for="TotalSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreamingUrl" class="control-label"></label>
                <input asp-for="StreamingUrl" class="form-control" />
                <span asp-validation-for="StreamingUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Image</label>
                <input type="hidden" asp-for="ImageId" />
            </div>
            <!-- Gallery -->
            <div class="row scrollable-gallery">
                @foreach (var image in (IEnumerable<VMImage>)ViewBag.Images)
                {
                    <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
                        <img id="image@image.Id"
                         src="@image.Content"
                         class="w-100 shadow-1-strong rounded mb-4"
                         alt="Image"
                         onclick="selectImage('@image.Id', this); viewImage('@image.Content');"
                         style="cursor: pointer;" />
                    </div>
                }
            </div>
            <!-- Gallery -->
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />   <a class="btn btn-warning" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="imageModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <img id="modalImage" class="img-fluid" src="" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var selectedImage = null;

        function selectImage(imageId, element) {
            document.getElementById('ImageId').value = imageId;

            if (selectedImage != null) {
                selectedImage.classList.remove('selected');
            }

            element.classList.add('selected');
            selectedImage = element;
        }

        function viewImage(imageSrc) {
            document.getElementById('modalImage').src = imageSrc;
            $('#imageModal').modal('show');
        }
    </script>
}

AdminModule/Views/Video/Index.cshtml
@using System.Text;
@using AdminModule.Pages;
@model IEnumerable<VMVideo>

@{
    ViewData["Title"] = "Index";
    int numRows = 3;
    int cardsPerRow = Model.ToList().Count / numRows;

    Pager pager = new Pager();
    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

}

<h1>Videos</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Add video</a> <a class="btn btn-primary" asp-action="Index" asp-route-clearFilter="true">Clear Search</a>
</p>

@using (Html.BeginForm("Index", "Video", FormMethod.Get))
{
    <div class="input-group rounded">
        <input type="search" class="form-control rounded" id="searchQuery" name="searchQuery" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
        <span class="input-group-text border-0" id="search-addon">
            <i class="fas fa-search"></i>
        </span>
    </div>

    <br>
    <div class="containter">
        @if (pager.TotalPages > 0)
        {
            <h4>Page:</h4>
            <ul class="pagination justify-content-lg-begin">
                @for (var pg = pager.StartPage; pg <= pager.EndPage; pg++)
                {
                    <li class="page-item @(pg == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Video" asp-action="Index" asp-route-page="@pg" asp-route-sortOrder="@ViewBag.CurrentSortOrder">@pg</a>
                    </li>
                }
            </ul>
        }
    </div>
}



<br>
<div>
    <div>
        <strong>Sort by:</strong>
        <select id="sortOrder" onchange="location = this.value;">
            <option value="">Select...</option>
            <option value="@Url.Action("Index", new { sortOrder = "Name" })">Name</option>
            <option value="@Url.Action("Index", new { sortOrder = "Genre" })">Genre</option>

            <option value="@Url.Action("Index", new { sortOrder = "Name desc" })">Name desc</option>
            <option value="@Url.Action("Index", new { sortOrder = "Genre desc" })">Genre desc</option>

        </select>
    </div>
</div>

<br>

@foreach (var video in Model)
{
    StringBuilder sb = new StringBuilder();
    string tags;
    var timeConvert = video.TotalSeconds / 60;
    foreach (var tag in video.VideoTags)
    {
        sb.Append("[" + tag.Tag.Name + "]");
    }
    tags = sb.ToString();
    <div class="card text-lg-start">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="@video.Image.Content" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">@video.Name</h5>
                    <p class="card-text">Description: @video.Description</p>
                    <p class="card-text">Duration: @timeConvert mins</p>
                    <a href="@video.StreamingUrl" class="card-link">Video link</a>
                    <p class="card-text">Genre: @video.Genre.Name</p>
                    <p class="card-text">Tags: @tags</p>
                    @Html.ActionLink("Edit", "Edit", new { id = video.Id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Delete", "Delete", new { id = video.Id }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            Added on: @video.CreatedAt;
        </div>
    </div>
    <br />
}

@section Scripts {
    @{
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                document.getElementById('pageSize').value = '@ViewBag.PageSize';
            });
        </script>
    }
}